
@echo off

REM !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!

md MagicPhotoDummyLayout\Assets\3rd\fmp-xtc-magicphotodummylayout

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-magicphotodummylayout-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\MagicPhotoDummyLayout\Assets\3rd\fmp-xtc-magicphotodummylayout\
